name: pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o Python 3.12
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'